### ISSUE TITLE
Declaring a tuple in a loop with the return value from an external function does not update the tuple value after the first call

### ISSUE THREAD

**Issue by sornas** [FredTheDino/sylt-lang#298]
https://github.com/FredTheDino/PuckNet/commit/95f32c6e49284fc98020c910fab4b831173868b1

**Comment by FredTheDino** [comment]
So this bug is surprisingly complex. The original error was that `break` and `continue` were improperly implemented in the compiler. BUT they were implemented to support an invariant - namely that no varaiable can be popped from two places. This is what breaks the typechecker and is a limitation in the way we've implemented it.

So we need something to disable the typechecker for cirtain tests to properly verify this - until we rewrite the typesystem.
