### ISSUE TITLE
Multiple files

### ISSUE THREAD

**Issue by FredTheDino** [FredTheDino/sylt-lang#79]
We would like to write code in multiple files, and then link this up!
Maybe something like this:

a.sy
```sylt
f :: fn {
    print "Hello world!"
}
```

b.sy
```sylt
from a import f
f()  // Hello world!
```

**Comment by sornas** [comment]
We discussed a few options and goals with this:

("Include" in the following is just a term. AFAIK we haven't decided on a keyword.)

- We want to avoid include ordering. Especially with game jams you want things to Just Work. 
- You also don't want to care about circular dependencies. You don't want to loft declarations to a third file _just_ because both file A and file B need it.
- On the other hand, this raises issues with code that is written in the outer-most scope. What does an include _mean_ in this case? The closest I can get to describe our consensus is that all statements have to be located in a function and that we automatically run a function named "main" when a file is run.
- We export constant functions (including closures) and type definitions (blobs). Variables need getters and setters.
- Probably more that I've forgotten. (Please add!)

Standing questions:

- Automatic modules when importing? Something like how Python does it.
```py
import a
a.f()

from a import f
f()
```

**Comment by FredTheDino** [comment]
Because of how the compiler is written, this is simply not possible at the moment. We need to introduce sweeping changes to get to no-include ordering, namely a second pass.

We can do this, but it will require a lot of rewriting and restructuring. Restructuring we might need.
